import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "FinTrack Admin",
    template: "%s | FinTrack Admin",
  },
  description:
    "FinTrack Admin Panel — a modern dashboard for managing users, finances, and analytics with precision and control.",

  keywords: [
    "FinTrack",
    "Admin Panel",
    "Finance Dashboard",
    "Expense Tracker",
    "Analytics",
  ],

  authors: [{ name: "Satinder Singh Sall" }],

  creator: "Satinder Singh Sall",

  metadataBase: new URL("https://fintrack-adminpanel.vercel.app"),

  openGraph: {
    title: "FinTrack Admin Panel",
    description:
      "Manage users, finances, and analytics with a modern and powerful admin dashboard.",
    url: "https://fintrack-adminpanel.vercel.app",
    siteName: "FinTrack Admin",
    images: [
      {
        url: "/og-image.png", // add later
        width: 1200,
        height: 630,
        alt: "FinTrack Admin Dashboard",
      },
    ],
    locale: "en_US",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "FinTrack Admin Panel",
    description:
      "A premium admin dashboard for finance and analytics management.",
    images: ["/og-image.png"],
  },

  icons: {
    icon: "/favicon.ico",
  },
};

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
